[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions" # Functionsのディレクトリを指定

[dev]
  command = "vite"
  port = 3000

[[redirects]]
  from = "/api/gas/*"
  to = "/.netlify/functions/gas-proxy" # プロキシ関数へのパス
  status = 200
  force = true
