[build]
  command = "npm --prefix client install && npm --prefix client run build"
  publish = "client/dist"
  functions = "./netlify/functions"

[dev]
  command = "vite"
  port = 3000

[[redirects]]
  from = "/api/gas/*"
  to = "/.netlify/functions/gas-proxy" # プロキシ関数へのパス
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
